### ISSUE TITLE
MongoDB Configuration

### ISSUE THREAD

**Issue by CharlieMahana** [UTDNebula/nebula-api#31]
I recently updated our MongoDB clusters to serverless instances and conducted several changes. Among these changes, I decided that it would be best to separate degrees, courses, sections, and professors into separate databases. Since mongoose defaults to one database connection by default, we will have to implement in a way to load a connection to each individual database when the API starts.

**Tasks**
- [ ] Design a way to effectively initialize a connection to each database when the API starts that is easily extendable and maintainable as the number of databases increase. These connections should be easily accessible.
- [ ] Develop a function that can be run when the API starts achieving what is described above.
- [ ] Update current models to support new database connections
